# Generated by Django 5.0.4 on 2024-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phoneNO', models.PositiveIntegerField()),
                ('role', models.TextField()),
                ('comments', models.TextField(max_length=1000)),
                ('celebrities', models.TextField()),
            ],
        ),
    ]
