# Generated by Django 5.0.4 on 2024-04-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='phoneNO',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
